name: lint

on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v2
    - run: make lint
=======
    - run: make lint
>>>>>>> refs/remotes/origin/main
